### ISSUE TITLE
C#-ify the bindings?

### ISSUE THREAD

**Issue by mathew-odwyer** [hasali19/SharpSDL#1]
I think it would be a good idea to make the methods, enums and such a little more C# friendly:

```csharp
// Instead of
SDL.SDL_Init(SDL_InitFlags.SDL_INIT_EVERYTHING);

// Change it to
SDL.Init(InitFlags.Everything);
```

**Comment by hasali19** [comment]
I think I would actually prefer that now. I was originally just trying to match the original SDL style as closely as possible but I agree it's kind of ugly.

I've been planning to do a v2 which replaces the delegates with DllImports and uses the new `NativeLibrary` class for .NET Core 3.0. I can also update the style when I do this.

**Comment by mathew-odwyer** [comment]
@hasali19, I think maybe you should use [ADL](https://github.com/Firwood-Software/AdvancedDLSupport) to continue allowing use of the bindings on .NET Standard. Whichever way you decide to go I'd love to help.

**Comment by hasali19** [comment]
Thanks for the link. I actually saw that library a while back, although I'm not sure that it's much better than just using `DllImport`s.

The `NativeLibrary` stuff will only be compiled for .NET Core 3.0. On other platforms, the usual search behaviour for `DllImport`s will still apply, so .NET Standard should continue to be supported.

**Comment by mathew-odwyer** [comment]
@hasali19, I see you're at work on V2, now.

How far along are you? :)

**Comment by hasali19** [comment]
I just haven't got round to fully testing the new loading code. Thanks for reminding me though, I might do a release today if I can.

**Comment by mathew-odwyer** [comment]
@hasali19, if you do that, I'd be forever grateful 😄

**Comment by mathew-odwyer** [comment]
@hasali19  and you could close my issue haha!

**Comment by mathew-odwyer** [comment]
@hasali19, one thing I did just notice though is...

```csharp
[DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
public static extern int Init(InitFlags flags);
```

You updated the method signatures throughout the project, but you never specified an entry point for them, shouldn't it be:

```csharp
[DllImport(LibraryName, EntryPoint = "SDL_Init", CallingConvention = CallingConvention.Cdecl)]
public static extern int Init(InitFlags flags);
```

**Comment by hasali19** [comment]
Huh, I could've sworn I tested at least that much, thanks for catching that!

Unfortunately, I'm really busy for the next couple of days, so I might not be able to deal with this until the weekend. Hopefully, I will get a chance to do it then. Sorry about that!

**Comment by hasali19** [comment]
This is now merged and pushed to NuGet.
